name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Deploy the web dyno"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: cacpodbot
          heroku_email: "gabrieldma2004@gmail.com"
          justlogin: true

      - name: "Login to heroku registry"
        run: heroku login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app cacpodbot

      - name: "Releases the container"
        run: heroku container:release web --app cacpodbot
